### ISSUE TITLE
Session issues

### ISSUE THREAD

**Issue by xion87** [vik1395/BungeeAuth-Minecraft#3] opened 2016-09-13 08:40 UTC
1) Sometimes user is not teleported to the lobby when he return
2) When other user with different ip log into the session time, it will be teleported to lobby (lucky he can't do anything) and asking him to login, teleport should be cancelled
3) Feature request: allow session to be disabled, puting 0 or -1 do nothing for now

**Comment by vik1395** [comment] 2016-09-13 23:09
1) Make sure you set "force_default_server" to true in BungeeCord's config.yml.
2) I am not really sure what the issue is that you are facing. Could you explain it a but more please?
3) Just set "Session Length" to 0 in BungeeAuth's config.yml.

If the issues still aren't fixed, and you get error logs with any of the issues you have mentioned above, please attach them here so I can take a look at what's going on.

**Comment by xion87** [comment] 2016-09-14 08:17
1) force default server is already active, sometimes it fail to teleport to the hub, because the bungee "force server" will race with bungeeauth teleporter
2) So i explain:
Viki join a server, where is installed bungeeauth, there is a session configured about 5 minutes. Viki logout, after 1 minute a bad guy try to log with Viki account, when he enter in the server, it will be teleported to the hub (like the session does), but he can't do anything since he need to login, (and lucky i have force gamemode 2 at hub so he can't break blocks also he is staff).
3) Already tried to do that, it continue to be a 1 minute session

And about errors i don't have any except the warnings that i reported #4

**Comment by vik1395** [comment] 2016-09-15 03:55
Alright, so in the first two cases, there is an issue with the plugin not being able to teleport the player to the right server?

**Comment by xion87** [comment] 2016-09-15 07:29
exact, example now i logout, i got session set to 0, i come back and i was stuck in login server and saying "session resumed" without be teleported to hub  server. (is broken as i say)
And also when i type /logut there is no kick countdown (not sure if is normal)
When somesone during session time log with different ip, it must teleport the user to the login server.

**Comment by xion87** [comment] 2016-10-01 17:13
I suspect this issue is related with priority event that is from https://www.spigotmc.org/threads/bungeealiases.50488/page-2

**Comment by vik1395** [comment] 2016-10-01 18:33
I actually had a discussion about this with the people on IRC and they seem to agree with me. The whole priorities thing is a little vague though. 

I am working on making the plugin more secure though, so those problems you came across should be minimized

**Comment by vik1395** [comment] 2016-10-02 06:37
The issues you have reported were fixed in https://github.com/vik1395/BungeeAuth-Minecraft/commit/84b2c665f2f4f46679481a605f9c1ab45bf14a8b and https://github.com/vik1395/BungeeAuth-Minecraft/commit/2648ff4273c51caf46433452258fb7369890de54

Setting guest session to 0 will disable the time limit.
The issue with player not being teleport correctly should be minimized. If a non logged-in player enters the server and is not teleported to authlobby, then they will be kicked from the server.

**Closed by vik1395** 2016-10-02 06:37 UTC
Labels: bug

**Comment by vik1395** [comment] 2016-10-02 22:00
There was an issue with server teleportation in the update earlier. I have fixed this issue now. Please redownload the jar file to get the latest fix.
